spring:
  datasource:
    #https://www.baeldung.com/spring-boot-h2-database
    url: jdbc:h2:file:./h2-bricks;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      ddl-auto: update
      format_sql: true
#    initialization-mode: never
#    schema: initial-schema.sql
#    data: initial-data.sql
  h2:
    #Starts the Web Console at http://localhost:8080/h2-console
    console.enabled: true

  jackson:
    #default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
      indent_output: true

catalog:
  load-on-startup: false
  resources:
    bricklink: #Resources must be loaded in this order
      colors: classpath:bricklink/colors.txt
      categories: classpath:bricklink/categories.txt
      elements: classpath:bricklink/Parts.txt
      piece: classpath:bricklink/codes.txt
    franchise: classpath:franchise.csv