spring:
  server.tomcat:
    connection-timeout: 600000
  datasource:
    #https://www.baeldung.com/spring-boot-h2-database
    url: jdbc:h2:file:./h2-bricks;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    #    properties:
    #      hibernate.cache.use_second_level_cache: true
    #      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      ddl-auto: update
      format_sql: true
      initialization-mode: always
  #    schema: initial-schema.sql
  #    data: initial-data.sql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
          event:
            merge:
              entity_copy_observer: allow

  h2:
    #Starts the Web Console at http://localhost:8080/h2-console
    console.enabled: true

  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      write-dates-as-timestamps: false
      indent_output: true

bricks:
  queries:
    countries:
      sql: "select c.ALPHA3, count(*) from franchise f join country c ON c.ALPHA3 = f.COUNTRY_ALPHA3 GROUP BY c.ALPHA3"
      columns: "Country,Stores"

catalog:
  rebrickable: #Resources must be loaded in this order
    colors: https://cdn.rebrickable.com/media/downloads/colors.csv.gz
    themes: https://cdn.rebrickable.com/media/downloads/themes.csv.gz
    part-categories: https://cdn.rebrickable.com/media/downloads/part_categories.csv.gz
    parts: https://cdn.rebrickable.com/media/downloads/parts.csv.gz
    elements: https://cdn.rebrickable.com/media/downloads/elements.csv.gz
    sets: https://cdn.rebrickable.com/media/downloads/sets.csv.gz
    minifigs: https://cdn.rebrickable.com/media/downloads/minifigs.csv.gz
    minifigs-inventories: https://cdn.rebrickable.com/media/downloads/inventory_minifigs.csv.gz
    inventories: https://cdn.rebrickable.com/media/downloads/inventories.csv.gz
    inventories-parts: https://cdn.rebrickable.com/media/downloads/inventory_parts.csv.gz